import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val auto_service: String = "com.google.auto.service:auto-service:" +
            Versions.com_google_auto_service

    const val auto_service_annotations: String =
            "com.google.auto.service:auto-service-annotations:" + Versions.com_google_auto_service

    /**
     * https://github.com/tbroyer/gradle-incap-helper
     */
    const val incap: String = "net.ltgt.gradle.incap:incap:" + Versions.net_ltgt_gradle_incap

    /**
     * https://github.com/tbroyer/gradle-incap-helper
     */
    const val incap_processor: String = "net.ltgt.gradle.incap:incap-processor:" +
            Versions.net_ltgt_gradle_incap

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" +
            Versions.io_gitlab_arturbosch_detekt_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val nebula_nebula_bintray_gradle_plugin: String =
            "nebula.nebula-bintray:nebula.nebula-bintray.gradle.plugin:" +
            Versions.nebula_nebula_bintray_gradle_plugin

    const val nebula_maven_publish_gradle_plugin: String =
            "nebula.maven-publish:nebula.maven-publish.gradle.plugin:" +
            Versions.nebula_maven_publish_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
            Versions.org_jetbrains_dokka_gradle_plugin

    const val nebula_project_gradle_plugin: String =
            "nebula.project:nebula.project.gradle.plugin:" + Versions.nebula_project_gradle_plugin

    const val nebula_release_gradle_plugin: String =
            "nebula.release:nebula.release.gradle.plugin:" + Versions.nebula_release_gradle_plugin

    /**
     * https://junit.org/junit5/
     */
    const val junit_platform_launcher: String = "org.junit.platform:junit-platform-launcher"

    /**
     * https://junit.org/junit5/
     */
    const val junit_vintage_engine: String = "org.junit.vintage:junit-vintage-engine"

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    const val spigot_api: String = "org.spigotmc:spigot-api:" + Versions.spigot_api

    /**
     * https://junit.org/junit5/
     */
    const val junit_bom: String = "org.junit:junit-bom:" + Versions.junit_bom

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * http://github.com/google/truth
     */
    const val truth: String = "com.google.truth:truth:" + Versions.truth
}
